name: Workflow for QA Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Check node and npm versions
        run: |
          node -v
          npm -v

      - name: Resolve Dependencies
        run: npm install

      - name: Build React App
        run: npm run build-react

      - name: Run tests
        run: npm run test-react

      - name: Run Linting
        run: npx eslint src/sum.js src/cartview.js src/shippingOptions.js
          
      - name: Deploy Changes
        if: ${{ success() }}
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/
          remote_host: 54.82.216.193
          remote_user: ubuntu
          remote_key: ${{ secrets.TEST_SERVER_KEY }}
